enum UserRole {
  superAdmin,
  owner,
  admin,
  manager,
  cashier,
}

enum Permission {
  // Billing
  createBill,
  viewBill,
  voidBill,
  refundBill,
  discountOverride,
  parkBill,
  quickBill,

  // Inventory
  addProduct,
  editProduct,
  deleteProduct,
  viewProduct,
  importProducts,
  exportProducts,
  printBarcode,
  stockAdjustment,

  // Customers
  addCustomer,
  editCustomer,
  viewCustomer,
  deleteCustomer,
  sendPromo,
  createCoupon,

  // Suppliers
  addSupplier,
  editSupplier,
  viewSupplier,
  deleteSupplier,

  // Cash Management
  openBalance,
  cashIn,
  cashOut,
  closeRegister,

  // Expenses
  addExpense,
  viewExpense,
  deleteExpense,

  // Reports
  viewSalesReport,
  viewTaxReport,
  viewProfitReport,
  exportReport,

  // Team
  addUser,
  editUser,
  deleteUser,
  viewUser,
  resetPassword,
  viewSalesAttribution,
  assignRole,

  // Settings
  editStoreProfile,
  managePrinter,
  manageOpenWA,
  backupRestore,
  secureErase,
  viewSubscription,

  // Super Admin
  viewAllShops,
  manageSubscription,
  viewRevenue,

  // General
  viewDashboard,
  viewReports,
}

class PermissionChecker {
  static const Map<UserRole, List<Permission>> _rolePermissions = {
    UserRole.superAdmin: Permission.values,
    UserRole.owner: [
      Permission.createBill,
      Permission.viewBill,
      Permission.voidBill,
      Permission.refundBill,
      Permission.discountOverride,
      Permission.parkBill,
      Permission.quickBill,
      Permission.addProduct,
      Permission.editProduct,
      Permission.deleteProduct,
      Permission.viewProduct,
      Permission.importProducts,
      Permission.exportProducts,
      Permission.printBarcode,
      Permission.stockAdjustment,
      Permission.addCustomer,
      Permission.editCustomer,
      Permission.viewCustomer,
      Permission.deleteCustomer,
      Permission.sendPromo,
      Permission.createCoupon,
      Permission.addSupplier,
      Permission.editSupplier,
      Permission.viewSupplier,
      Permission.deleteSupplier,
      Permission.openBalance,
      Permission.cashIn,
      Permission.cashOut,
      Permission.closeRegister,
      Permission.addExpense,
      Permission.viewExpense,
      Permission.deleteExpense,
      Permission.viewSalesReport,
      Permission.viewTaxReport,
      Permission.viewProfitReport,
      Permission.exportReport,
      Permission.addUser,
      Permission.editUser,
      Permission.deleteUser,
      Permission.viewUser,
      Permission.resetPassword,
      Permission.viewSalesAttribution,
      Permission.assignRole,
      Permission.editStoreProfile,
      Permission.managePrinter,
      Permission.manageOpenWA,
      Permission.backupRestore,
      Permission.secureErase,
      Permission.viewSubscription,
      Permission.viewDashboard,
      Permission.viewReports,
    ],
    UserRole.admin: [
      Permission.createBill,
      Permission.viewBill,
      Permission.voidBill,
      Permission.refundBill,
      Permission.discountOverride,
      Permission.parkBill,
      Permission.quickBill,
      Permission.addProduct,
      Permission.editProduct,
      Permission.deleteProduct,
      Permission.viewProduct,
      Permission.importProducts,
      Permission.exportProducts,
      Permission.printBarcode,
      Permission.stockAdjustment,
      Permission.addCustomer,
      Permission.editCustomer,
      Permission.viewCustomer,
      Permission.sendPromo,
      Permission.createCoupon,
      Permission.addSupplier,
      Permission.editSupplier,
      Permission.viewSupplier,
      Permission.openBalance,
      Permission.cashIn,
      Permission.cashOut,
      Permission.closeRegister,
      Permission.addExpense,
      Permission.viewExpense,
      Permission.deleteExpense,
      Permission.viewSalesReport,
      Permission.viewTaxReport,
      Permission.viewProfitReport,
      Permission.exportReport,
      Permission.viewUser,
      Permission.editStoreProfile,
      Permission.managePrinter,
      Permission.manageOpenWA,
      Permission.backupRestore,
      Permission.viewSubscription,
      Permission.viewDashboard,
      Permission.viewReports,
    ],
    UserRole.manager: [
      Permission.createBill,
      Permission.viewBill,
      Permission.refundBill,
      Permission.parkBill,
      Permission.quickBill,
      Permission.viewProduct,
      Permission.printBarcode,
      Permission.stockAdjustment,
      Permission.addCustomer,
      Permission.editCustomer,
      Permission.viewCustomer,
      Permission.viewSupplier,
      Permission.cashIn,
      Permission.cashOut,
      Permission.viewExpense,
      Permission.viewSalesReport,
      Permission.viewTaxReport,
      Permission.viewProfitReport,
      Permission.viewDashboard,
      Permission.viewReports,
    ],
    UserRole.cashier: [
      Permission.createBill,
      Permission.viewBill,
      Permission.quickBill,
      Permission.viewProduct,
      Permission.viewCustomer,
      Permission.viewDashboard,
    ],
  };

  static bool hasPermission(UserRole role, Permission permission) {
    final permissions = _rolePermissions[role];
    return permissions?.contains(permission) ?? false;
  }
}
